spring:
  data:
    mongodb:
      database: ${MONGODB_DATABASE:userverse}
      uri: ${MONGODB_URI:mongodb://localhost:27017}
springdoc:
  server:
    url: http://localhost:2000
    description: "Localhost server"